---
username: '{{ username }}'
safe_interval: 10
proxy_command: ssh -q -Y {{ username }}@ela.cscs.ch netcat eiger.cscs.ch 22
key_filename: ~/.ssh/cscs-key
key_policy: AutoAddPolicy
metadata:
    tooltip: |
        <p>
            Setup up the SSH connection.
        </p>
    ssh_auth: 2FA
    template_variables:
        username:
            description: The username to use for the SSH connection
            type: text
            key_display: SSH username
